tap "carlocab/personal"
tap "dagger/tap"
tap "elastic/tap"
tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jimihford/hendrix"
tap "junk16/custom"
tap "kaos/shell"
tap "kegworks-app/kegworks"
tap "modularml/packages"
tap "mongodb/brew"
tap "netmute/tap"
tap "robotsandpencils/made"
tap "shivammathur/php"
tap "spring-io/tap"
tap "universal-ctags/universal-ctags"
brew "anyenv"
brew "libpng"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "pcre2"
brew "apachetop"
brew "autoconf"
brew "automake"
brew "boost"
brew "libusb"
brew "avrdude"
brew "bash"
brew "bat"
brew "bats-core"
brew "bison"
brew "bzip2"
brew "freetype"
brew "gettext"
brew "glib"
brew "cairo"
brew "cmake"
brew "libtool"
brew "unixodbc"
brew "freetds"
brew "libzip"
brew "tidy-html5"
brew "php"
brew "composer"
brew "cpanminus"
brew "csshx"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "docker-ls"
brew "python@3.12"
brew "docutils"
brew "efm-langserver"
brew "ems-flasher"
brew "faac"
brew "fd"
brew "flac"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "libmicrohttpd"
brew "librist"
brew "pango"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "filebeat"
brew "fs-uae"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gdk-pixbuf"
brew "ghostscript"
brew "ghq"
brew "gibo"
brew "git"
brew "git-delta"
brew "git-flow"
brew "git-lfs"
brew "global"
brew "gnu-sed"
brew "go"
brew "pkgconf"
brew "gobject-introspection"
brew "gperftools"
brew "gradle"
brew "grafana"
brew "netpbm"
brew "librsvg"
brew "graphviz"
brew "grep"
brew "groonga"
brew "gtk4"
brew "guile"
brew "handbrake"
brew "ifstat"
brew "libheif"
brew "libraw"
brew "imagemagick"
brew "influxdb"
brew "jack"
brew "jmeter"
brew "jq"
brew "kubernetes-cli"
brew "lazygit"
brew "less"
brew "libedit"
brew "libffi"
brew "libfido2"
brew "libgcrypt"
brew "libiconv"
brew "libmemcached"
brew "libxml2"
brew "lima"
brew "llvm"
brew "luajit"
brew "luarocks"
brew "lzip"
brew "man2html"
brew "mariadb", restart_service: :changed
brew "mas"
brew "maven"
brew "memcached"
brew "minipro"
brew "qt"
brew "mkvtoolnix"
brew "node"
brew "mongosh"
brew "neovim"
brew "nghttp2"
brew "nginx"
brew "nkf"
brew "ollama", restart_service: :changed
brew "onefetch"
brew "openjdk@17"
brew "openjdk@21"
brew "openmsx"
brew "pdftk-java"
brew "peco"
brew "perl"
brew "pipenv"
brew "plantuml"
brew "podman"
brew "postgresql@14"
brew "pstree"
brew "py3cairo"
brew "qt@5"
brew "pyqt@5"
brew "qcachegrind"
brew "qemu"
brew "qpdf"
brew "r"
brew "re2c"
brew "redis"
brew "rename"
brew "ripgrep"
brew "rpm2cpio"
brew "rsync"
brew "ruby"
brew "rustup"
brew "shellcheck"
brew "sonarqube"
brew "sox"
brew "task"
brew "telnet"
brew "tldr"
brew "tmux"
brew "tree"
brew "vegeta"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"
brew "youtube-dl"
brew "yt-dlp"
brew "zellij"
brew "zlib"
brew "dagger/tap/dagger"
brew "elastic/tap/elasticsearch-full"
brew "jimihford/hendrix/unnks"
brew "kaos/shell/bats-assert"
brew "kaos/shell/bats-file"
brew "mongodb/brew/mongodb-community"
brew "netmute/tap/ctags-lsp"
brew "robotsandpencils/made/xcodes"
brew "shivammathur/php/php@7.3"
brew "spring-io/tap/spring-boot"
cask "anki"
cask "appcleaner"
cask "arduino"
cask "au-lab"
cask "audacity"
cask "blackhole-16ch"
cask "blackhole-2ch"
cask "blackhole-64ch"
cask "bruno"
cask "burn"
cask "calibre"
cask "chromedriver"
cask "claude"
cask "cyberduck"
cask "devtoys"
cask "dosbox-x"
cask "dotnet-sdk"
cask "eagle"
cask "firefox"
cask "flycast"
cask "font-caskaydia-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "freecad"
cask "fs-uae"
cask "fs-uae-launcher"
cask "ftdi-vcp-driver"
cask "ghidra"
cask "gimp"
cask "google-chrome"
cask "grandperspective"
cask "gstreamer-runtime"
cask "handbrake"
cask "iterm2"
cask "karabiner-elements"
cask "kegworks"
cask "kicad"
cask "librecad"
cask "lm-studio"
cask "locationsimulator"
cask "ltspice"
cask "mactex"
cask "makemkv"
cask "mist"
cask "obs"
cask "ocenaudio"
cask "openemu"
cask "pd"
cask "processing"
cask "rar"
cask "supercollider"
cask "td-agent"
cask "utm"
cask "viber"
cask "vimr"
cask "visual-studio-code"
cask "vlc"
cask "whisky"
cask "wine-stable"
cask "xld"
cask "xquartz"
cask "yacreader"
mas "Adblock Plus", id: 1432731683
mas "AdBlock Pro", id: 1018301773
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "CotEditor", id: 1024640650
mas "Couverture", id: 1552415914
mas "CrystalFetch", id: 6454431289
mas "Dipper", id: 6450242673
mas "Display Menu", id: 549083868
mas "EasyRes", id: 688211836
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "Hex Fiend", id: 1342896380
mas "Hotspot Shield", id: 771076721
mas "iMazing Converter", id: 1292198261
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle Classic", id: 405399194
mas "LadioCast", id: 411213048
mas "LINE", id: 539883307
mas "Memory Clean 2", id: 1114591412
mas "Microsoft Remote Desktop", id: 1295203466
mas "MIDI Loupe", id: 507075182
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "Pages", id: 409201541
mas "QuickFTP", id: 1451646819
mas "Save to Pocket", id: 1477385213
mas "Save to Raindrop.io", id: 1549370672
mas "Session Pal", id: 1515213004
mas "Smart JSON Editor", id: 1268962404
mas "Tabstract", id: 6743376666
mas "The Unarchiver", id: 425424353
mas "Userscripts-Mac-App", id: 1463298887
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
vscode "bmewburn.vscode-intelephense-client"
vscode "mechatroner.rainbow-csv"
vscode "naco-siren.gradle-language"
vscode "oracle.oracle-java"
vscode "redhat.java"
vscode "rianadon.vscode-java-checkstyle"
vscode "richardwillis.vscode-gradle-extension-pack"
vscode "shengchen.vscode-checkstyle"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscjava.vscode-spring-initializr"
vscode "vscodevim.vim"
