tap "carlocab/personal"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
#tap "junk16/custom"
#tap "junk16/old-openssl"
tap "kaos/shell"
tap "robotsandpencils/made"
tap "universal-ctags/universal-ctags"

brew "neovim"
brew "python@3.10"
brew "ansible"
brew "anyenv"
brew "webp"
brew "apachetop"
brew "autoconf"
brew "automake"
brew "libusb"
brew "avrdude"
brew "bash"
brew "bat"
brew "bats-core"
brew "boost"
brew "gettext"
brew "libffi"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "cairo"
brew "cmake"
brew "csshx"
brew "direnv"
brew "docker-compose"
brew "docutils"
#brew "elasticsearch", restart_service: false
brew "ems-flasher"
brew "faac"
brew "flac"
brew "guile"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "little-cms2"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "filebeat"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gdb"
brew "gdk-pixbuf"
brew "ghq"
brew "gibo"
brew "git"
brew "git-delta"
brew "git-flow"
brew "git-lfs"
brew "gnu-sed"
brew "gperftools"
#brew "grafana", restart_service: false
brew "netpbm"
brew "python@3.8"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "nghttp2"
brew "httpd", restart_service: false
brew "ifstat"
brew "libheif"
brew "imagemagick"
brew "influxdb"
brew "jack"
brew "jmeter"
brew "jq"
#brew "zookeeper", restart_service: false
#brew "kafka", restart_service: false
#brew "kibana", restart_service: false
brew "krb5"
brew "kubernetes-cli"
brew "lazygit"
brew "less"
brew "libmemcached"
brew "libxml2"
brew "qemu"
brew "lima"
brew "llvm"
brew "lzip"
brew "mas"
brew "maven"
brew "mcrypt"
#brew "md5sha1sum", link: false
brew "memcached"
brew "minipro"
brew "qt"
brew "mkvtoolnix"
brew "mysql"
brew "mysql@5.6"
brew "neovim"
brew "nginx"
brew "nkf"
brew "node"
#brew "node_exporter", restart_service: false
brew "pdftk-java"
brew "peco"
brew "perl"
brew "pipenv"
brew "plantuml"
brew "postgresql"
#brew "prometheus", restart_service: false
brew "pstree"
brew "qcachegrind"
brew "qpdf"
brew "r"
brew "re2c"
brew "redis"
brew "rename"
brew "rpm2cpio"
brew "rsync"
brew "ruby"
brew "shellcheck"
brew "task"
brew "telnet"
brew "tmux"
brew "tree"
brew "unixodbc"
brew "vegeta"
brew "vim"
brew "watch"
brew "wget"
brew "xhyve"
brew "yamllint"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "carlocab/personal/unrar"
#brew "junk16/old-openssl/openssl@1.0.2t"
brew "kaos/shell/bats-assert"
brew "kaos/shell/bats-file"
brew "robotsandpencils/made/xcodes"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

cask "vimr"
cask "iterm2"
cask "viber"
cask "au-lab"
cask "docker"
cask "ghidra"
cask "gimp"
cask "vmware-fusion"
cask "locationsimulator"
cask "td-agent"

mas "Adblock Plus", id: 1432731683
mas "AdBlock Pro", id: 1018301773
mas "Apple Configurator 2", id: 1037126344
mas "CotEditor", id: 1024640650
mas "Final Cut Pro", id: 424389933
mas "Hex Fiend", id: 1342896380
mas "Hotspot Shield", id: 771076721
mas "iMazing HEIC Converter", id: 1292198261
mas "iMovie", id: 408981434
mas "Kindle", id: 405399194
mas "LadioCast", id: 411213048
mas "LINE", id: 539883307
mas "Memory Clean 2", id: 1114591412
mas "Microsoft Remote Desktop", id: 1295203466
mas "Okta Extension App", id: 1439967473
mas "Save to Pocket", id: 1477385213
mas "Smart JSON Editor", id: 1268962404
mas "VisualJSON", id: 488709442
mas "Xcode", id: 497799835

